// ─────────────────────────────────────────────────────────────────────────────
// labels.ts — todos os textos visíveis ao usuário
// Para adicionar um novo idioma: crie um objeto com o mesmo tipo (Labels)
// e troque a linha final: export const t = pt → export const t = en
// ─────────────────────────────────────────────────────────────────────────────

const g = (n: number) => `gole${n !== 1 ? 's' : ''}`;
const e = (n: number) => `estrela${n !== 1 ? 's' : ''}`;

const pt = {
  common: {
    you: 'você',
    host: 'Host',
    guest: 'Guest',
    cancel: 'Cancelar',
    close: 'Fechar',
    confirm: 'Confirmar ✓',
    drank: 'Bebi! ✓',
    won: '🏆 Ganhei',
    lost: (drinks: number) => `😅 Perdi +${drinks}🍺`,
    goles: g,
    estrelas: e,
    multiplierNote: (x: number) => `(${x}x ativo)`,
  },

  lobby: {
    roomCode: 'Código da sala',
    qrTitle: 'Entrar na sala',
    leave: 'Sair',
    hostInstruction: 'Você é o host — aguarde os jogadores e inicie a partida.',
    guestWaiting: 'Aguardando o host iniciar...',
    players: (n: number) => `Jogadores (${n})`,
    choosingCharacter: 'escolhendo personagem...',
    startGame: '🎮 Começar Partida',
    waitingCharacters: 'Aguardando jogadores escolherem personagem...',
  },

  playersOverlay: {
    title: 'Jogadores',
    room: (code: string) => `Sala ${code}`,
    goles: 'goles',
  },

  playersStrip: {
    shieldTitle: 'Tem escudo',
  },

  boo: {
    title: 'Boo!',
    subtitle: 'O que o Boo roubou?',
    selectVictim: 'Selecione a vítima',
    stealStar: 'Roubou Estrela',
    stealStarYou: 'você +1⭐',
    stealStarVictim: (drinks: number) => `vítima −1⭐ +${drinks}🍺`,
    stealCoin: 'Roubou Dinheiro',
    stealCoinNote: 'sem mudança de ⭐',
    stealCoinVictim: (drinks: number) => `vítima bebe +${drinks}🍺`,
    com: 'COM',
    comSubtitle: 'bot / personagem NPC',
  },

  duel: {
    title: 'Duelo!',
    subtitle: (preDrink: number, loserDrinks: number) =>
      `Ambos bebem ${preDrink} antes. Perdedor bebe +${loserDrinks}`,
    preDuel: 'Pré-duelo (ambos)',
    loserDrinks: 'Perdedor bebe',
    multiplierNote: (x: number) => `multiplicador ${x}x ativo`,
    selectOpponent: 'Selecione o oponente',
    cpu: 'CPU / Outro',
    challenge: (drinks: number) => `⚔️ Desafiar — ${drinks}🍺`,
    resultTitle: 'Resultado do Duelo',
    vs: (name: string) => `vs ${name}`,
    loserDrinksResult: (drinks: number) => `Perdedor bebe +${drinks} goles`,
    multiplierResult: (x: number) => `(${x}x)`,
    cancelDuel: 'Cancelar duelo',
  },

  minigame: {
    formats: [
      { id: 'ffa',  label: 'FFA',  description: 'Último lugar bebe +1' },
      { id: '2v2',  label: '2v2',  description: 'Dupla perdedora bebe +1 cada' },
      { id: '1v3',  label: '1v3',  description: 'Lado perdedor bebe +1 cada' },
    ] as { id: string; label: string; description: string }[],
    hostTitle: '🎮 Fim do Turno',
    hostSubtitle: (turn: number) => `Turno ${turn}`,
    prebrewNotified: 'Pré-minigame notificado',
    prebrewNote: (drinks: number) => `Os outros já receberam para beber ${drinks} ${g(drinks)}`,
    formatLabel: 'Formato',
    startMinigame: 'Iniciar Minigame →',
    resultTitle: '🎮 Resultado',
    confirmLoss: (drinks: number) => `Confirmar derrota (+${drinks} ${g(drinks)})`,
    confirmWin: 'Confirmar vitória (nada a beber)',
    guestPrebrewTitle: '🍺 Pré-minigame!',
    guestPrebrewSubtitle: (hostName: string, turn: number) => `${hostName} encerrou o Turno ${turn}`,
    drinksBefore: (drinks: number) => `${drinks} ${g(drinks)} antes de começar`,
    drinkConfirm: 'Bebi! ✓ — Aguardar formato',
    waitingTitle: '⏳ Aguardando...',
    waitingSubtitle: 'Host está selecionando o formato',
    waitingBody: (hostName: string) => `${hostName} está escolhendo o formato do minigame...`,
    prebrewCounted: (drinks: number) => `🍺 ${drinks} ${g(drinks)} pré-minigame já contabilizados`,
    lost: '😅 Perdi',
  },

  incomingEvent: {
    titleAll: 'Todo mundo bebe!',
    titleYou: 'Você precisa beber!',
    useShield: 'Usar escudo 🛡️ — Dose pulada!',
    drank: (drinks: number) => `Bebi! ✓ (${drinks} ${g(drinks)})`,
  },

  spaceModal: {
    chanceTimeCard: 'Chance Time',
    chanceTimeQuestion: 'Você saiu prejudicado na troca?',
    chanceTimeYesNote: (drinks: number) => `Se sim, bebe mais ${drinks} ${g(drinks)}`,
    chanceTimeYes: (drinks: number) => `😖 Sim +${drinks}`,
    chanceTimeNo: '😊 Saí bem',
    effectLabel: 'Efeito no jogo',
    ruleLabel: 'Regra do Drinking Game',
    consequencesLabel: 'Consequências',
    youDrink: 'Você bebe',
    youDontDrink: 'Você não bebe',
    everyoneDrinks: 'Todo mundo bebe',
    othersDrink: 'Os outros bebem',
    notifyOthers: '🔔 Modal aparece no celular deles',
    extraDrinks: (n: number) => `+${n} goles extras`,
    extraDrinksNote: '(perguntará depois)',
    vsMinigame: 'Minigame VS!',
    vsMinigameRule: 'Todo mundo bebe 1 antes de jogar. Perdedor bebe +1.',
    shieldSkipOthers: 'Usar escudo 🛡️ — Pulei, mas notifico os outros',
    shieldSkipSelf: 'Usar escudo 🛡️ — Dose pulada!',
    drinkWithNotify: (drinks: number) => `Beber ${drinks} — modal aparece nos outros 🔔`,
    drinkConfirm: (drinks: number) => `Beber! 🍺 (${drinks} ${g(drinks)})`,
    confirmWithNotify: 'Confirmar — modal aparece nos outros 🔔',
    confirmLog: '✅ Confirmar — registrar no log',
    startVsMinigame: '🎮 Iniciar Minigame VS',
    vsMinigameLog: 'Casa VS — minigame iniciado!',
    extraDrinksUnit: 'goles extras',
    choiceYouDrink: (drinks: number) => `🍺 Você bebe ${drinks}`,
    choiceOthersDrink: (drinks: number) => `👥 Outros bebem ${drinks}`,
    choiceYouLog: (spaceName: string, drinks: number) => `${spaceName} — bebeu ${drinks} ${g(drinks)}`,
    choiceOthersLog: (spaceName: string) => `${spaceName} — os outros bebem 1`,
    choiceNotifies: 'notifica',
  },

  spacesSection: {
    title: 'Casas',
    drinkToast: (count: number) => `🍺 +${count} ${g(count)}!`,
    shieldUsed: 'Escudo usado! Dose pulada 🛡️',
  },

  diceSection: {
    title: 'Dado',
    rolled1: 'Tirei 1',
    rolled1Active: 'Já tem escudo!',
    rolled1Inactive: 'Ativa escudo',
    rolled10: 'Tirei 10',
  },

  starsSection: {
    events: [
      { label: 'Comprei estrela',  description: 'Comprou a estrela por 20 moedas' },
      { label: 'Estrela roubada',  description: 'Boo, Bowser, Chance Time...' },
      { label: 'Passei sem grana', description: 'Sem as 20 moedas na hora certa' },
    ] as { label: string; description: string }[],
    title: 'Estrelas',
    boo: 'Boo',
    booSubtitle: 'roubou estrela/grana',
    duel: 'Duelo',
    duelSubtitle: '1v1 com outro jogador',
    youDrink: 'Você bebe',
    goles: 'goles',
    starsLabel: 'Estrelas',
  },

  rulesSection: {
    title: 'Regras de Mesa',
    subtitle: '(consulta)',
    rules: [
      { title: 'Minigames',           content: 'Todo mundo bebe 1 gole antes de cada minigame. Perdedor bebe +1.' },
      { title: 'Formatos de Minigame', content: 'FFA: último bebe +1 | 2v2: dupla perdedora +1 cada | 1v3: lado perdedor +1 cada' },
      { title: 'Lucky Space',          content: 'Você caiu na casa da sorte? Todos os outros bebem 1 gole.' },
      { title: 'Chance Time',          content: 'Todo mundo bebe 1 gole. Quem saiu prejudicado na troca bebe +1.' },
      { title: 'Jamboree Buddy',       content: 'Ganhou um buddy? Os outros jogadores bebem 1 gole.' },
      { title: 'Bonus Star (final)',   content: 'Não ganhou nenhuma Bonus Star? 2 goles.' },
    ] as { title: string; content: string }[],
  },

  header: {
    turn: 'Turno',
    useShield: 'Usar escudo',
    undo: 'Undo',
    resetConfirm: 'Resetar o jogo? Isso apaga tudo.',
    resetHold: 'Segure para resetar',
    drinkMinus: '−',
    drinkPlus: '+',
    drinkOk: 'OK',
    drinkBack: 'Voltar',
    drinkGoles: 'goles',
    drinkPlus1: '+1 gole',
    drinkEdit: 'Editar goles',
    jamboree: 'Jamboree',
    jamboreeNote: '5 turnos',
  },

  endGame: {
    playAgain: 'Jogar de novo',
    close: 'Fechar',
    turnos: 'turnos',
    goles: 'goles',
    estrelas: 'estrelas',
    comments: [
      'Zero goles. Você jogou Mario Party sóbrio. Parabéns, acho.',
      'Um gole. Quase um brinde. Tá quente aí?',
      'Dois goles. Ainda contando. Que diligente.',
      'Três. Isso é o mínimo pro jogo ter sentido.',
      'Quatro goles. Uma base sólida. Continua.',
      'Cinco. Metade de uma lata. Tá ensaiando.',
      'Seis goles. Uma lata inteira. Hoje tá fácil.',
      'Sete. Número da sorte... ou do azar.',
      'Oito goles. Dois dedos a mais que o recomendado.',
      'Nove. Tá quase em dois dígitos. Vai fundo.',
      'Dois dígitos! Marco histórico. Desce mais.',
      'Onze. Começou a ficar interessante por aqui.',
      'Doze goles. Uma dúzia de más decisões.',
      'Treze. Número azarado pra quem cai no Bowser.',
      'Quatorze goles. A festa tá pegando fogo.',
      'Quinze. Meio caminho andado pra lenda.',
      'Dezesseis. O jogo já foi, você ficou.',
      'Dezessete. Alguém já avisou sua família?',
      'Dezoito. Maior de idade em goles. Parabéns.',
      'Dezenove. Um a mais e vira número redondo.',
      'Vinte goles. Vinte. Você tá bem?',
      'Vinte e um. BlackJack. Ganhou... mais goles.',
      'Vinte e dois. Não tem mais volta, amigo.',
      'Vinte e três. A noite vai ser muito longa.',
      'Vinte e quatro. Um gole por hora de sono perdido.',
      'Vinte e cinco. Metade de cinquenta. Deus te abençoe.',
      'Vinte e seis. Quem te conhecia antes dessa partida?',
      'Vinte e sete. Club dos 27. Território perigoso.',
      'Vinte e oito. Você ainda sabe o nome do jogo?',
      'Vinte e nove. Um a mais e trinta. Pensa bem.',
      'Trinta goles. Digno de uma estátua. De vergonha.',
      'Trinta e um. Agosto. Nem faz sentido mais.',
      'Trinta e dois. Você é uma lenda ou uma vítima?',
      'Trinta e três. Cristo tinha essa idade. Coincidência?',
      'Trinta e quatro. O Uber já deve estar a caminho.',
      'Trinta e cinco. O tapete vai girar daqui a pouco.',
      'Trinta e seis. Você pediu ajuda hoje? Não, né?',
      'Trinta e sete. Essa quantidade tem nome de doença.',
      'Trinta e oito. Os outros jogadores já foram embora?',
      'Trinta e nove. Um a mais e você vira mito urbano.',
      'Quarenta. Que Deus tenha misericórdia da sua alma.',
      'Quarenta e um. Tá vendo coisas? Pode ser normal.',
      'Quarenta e dois. A resposta pra tudo. Incluindo a sua ruína.',
      'Quarenta e três. Você ainda sabe onde mora?',
      'Quarenta e quatro. Alguém documenta isso, por favor.',
      'Quarenta e cinco. Amanhã vai ser difícil. E depois também.',
      'Quarenta e seis. Isso é uma conquista ou uma tragédia?',
      'Quarenta e sete. Você merece um troféu. De sofrimento.',
      'Quarenta e oito. Mantém um balde por perto.',
      'Quarenta e nove. UM. GOLE. A. MAIS.',
      'Cinquenta. C-I-N-Q-U-E-N-T-A. Você é uma obra de arte.',
    ] as string[],
    over50: 'Passou de cinquenta. Não existe número pra isso. Vai dormir.',
  },

  characterSelect: {
    title: 'Mario Party',
    subtitle: 'Drinking Game 🍺',
    subtitleRoom: 'Escolha seu personagem — personagens em uso estão bloqueados',
    subtitleOffline: 'Escolha seu personagem',
    inUse: 'em uso',
    confirm: 'Confirmar',
    playWith: (name: string) => `Jogar com ${name}!`,
    selectFirst: 'Selecione um personagem',
  },

  modeSelector: {
    title: 'Mario Party',
    subtitle: 'Drinking Game 🍺',
    offline: 'Jogar Sozinho',
    offlineNote: 'Modo offline, sem conexão',
    online: 'Criar / Entrar em Sala',
    onlineNote: 'Sincronizado com os amigos em tempo real',
  },

  roomEntry: {
    entering: (code: string) => `Entrando na sala ${code}...`,
  },

  roomEntryPage: {
    title: 'Entrar numa Sala',
    placeholder: 'Código da sala',
    join: 'Entrar',
    create: 'Criar Sala',
    orSeparator: 'ou',
    scanQr: 'Escanear QR Code',
    nicknamePlaceholder: 'Seu apelido (opcional)',
    back: 'Voltar',
    error: {
      notFound: 'Sala não encontrada. Verifique o código.',
      connection: 'Erro ao entrar na sala.',
    },
  },

  salaLayout: {
    booToast: (name: string, drinks: number, isStar: boolean) =>
      `👻 ${name} usou o Boo!${isStar ? ' -1⭐' : ''} +${drinks}🍺`,
    booLogStar: (name: string, drinks: number) =>
      `Boo de ${name} — perdeu ⭐ e bebeu ${drinks} ${g(drinks)}`,
    booLogCoin: (name: string, drinks: number) =>
      `Boo de ${name} — perdeu dinheiro e bebeu ${drinks} ${g(drinks)}`,
    duelCancelled: (name: string) => `⚔️ ${name} cancelou o duelo`,
    minigameSkipped: 'Host cancelou o minigame',
    minigameLostToast: (drinks: number) => `😅 Perdeu! 🍺 +${drinks}`,
    minigameLostLog: (drinks: number) => `Minigame — perdeu, bebeu ${drinks} ${g(drinks)}`,
    minigameWonToast: '🏆 Ganhou o minigame!',
    minigameWonLog: 'Minigame — ganhou!',
    prebrewToast: (drinks: number) => `🍺 +${drinks} (pré-minigame)`,
    prebrewLog: (drinks: number) => `Pré-minigame — bebeu ${drinks} ${g(drinks)}`,
    duelResultTitle: '⚔️ Duelo — resultado',
    duelWon: (name: string) => `${name} ganhou o duelo`,
    duelLostButton: (drinks: number) => `😅 Perdi — beber +${drinks}🍺`,
    duelLostToast: (drinks: number) => `😅 Perdeu o duelo! 🍺 +${drinks}`,
    duelLostLog: (challenger: string, drinks: number) =>
      `Perdeu o duelo com ${challenger} — bebeu ${drinks} ${g(drinks)}`,
    duelChallengedBy: (name: string) => `${name} te desafiou`,
    drinkBeforeDuel: 'Beba antes do duelo',
    preDuelMandatory: 'pré-duelo obrigatório',
    preDuelToast: (drinks: number) => `⚔️ +${drinks}🍺 (pré-duelo)`,
    preDuelLog: (name: string, drinks: number) =>
      `Desafio de ${name} — bebeu ${drinks} ${g(drinks)} (pré-duelo)`,
    drinkConfirm: 'Bebi! ✓',
    reconnecting: 'Reconectando à sala...',
    shieldUsed: 'Escudo usado! 🛡️',
    minigameTurn: (turn: number) => `🎮 Minigame — Turno ${turn}`,
    incomingDrinkLog: (msg: string, count: number) => `${msg} — bebeu ${count} ${g(count)}`,
    incomingShieldLog: (msg: string) => `Escudo usado — ${msg}`,
    prebrewHostLine: (hostName: string, turn: number) => `${hostName} · Turno ${turn}`,
    drinkBeforeMinigame: 'Beba antes do minigame',
    prebrewMandatory: 'pré-jogo obrigatório',
    waitingFormat: 'Aguardando formato...',
    formatLabels: {
      ffa:  'FFA — último lugar bebe +1',
      '2v2': '2v2 — dupla perdedora bebe +1 cada',
      '1v3': '1v3 — lado perdedor bebe +1 cada',
    } as Record<string, string>,
  },

  gameTracker: {
    alreadyHasShield: 'Já tem escudo! 🛡️',
    shieldActivated: 'Escudo ativado! 🛡️',
    shieldActivatedLog: 'Tirou 1 no dado — escudo ativado',
    luckyTax: (drinks: number) => `Imposto da sorte! 🎰 +${drinks} ${g(drinks)}`,
    luckyTaxLog: (drinks: number) => `Tirou 10 no dado — pagou ${drinks} ${g(drinks)}`,
    shieldUsed: 'Escudo usado! 🛡️ Comunique à mesa.',
    shieldUsedLog: 'Usou o escudo manualmente',
    tabGame: '🎮 Jogo',
    tabLog: '📋 Log',
    endTurn: (turn: number) => `🎮 Fim do Turno ${turn}`,
    waitingHost: 'Aguardando o host encerrar o turno...',
    endGame: '🏁 Fim de Partida',
    prebrewToast: (drinks: number) => `🍺 +${drinks} (pré-minigame)`,
    prebrewLog: (drinks: number) => `Pré-minigame — bebeu ${drinks} ${g(drinks)}`,
    minigameLostToast: (label: string, drinks: number) => `🎮 ${label} — perdeu! 🍺 +${drinks}`,
    minigameLostLog: (label: string, format: string, drinks: number) =>
      `${label} — ${format.toUpperCase()} — perdeu, bebeu ${drinks} ${g(drinks)}`,
    minigameWonToast: (label: string) => `🎮 ${label} — ganhou o minigame!`,
    minigameWonLog: (label: string, format: string) =>
      `${label} — ${format.toUpperCase()} — ganhou!`,
    vsLabel: 'Casa VS',
    turnLabel: (turn: number) => `Turno ${turn}`,
    undoLog: 'Desfez a última ação',
    drinkAdjustedToast: (v: number) => `✏️ Goles ajustados para ${v}`,
    drinkAdjustedLog: (v: number) => `Ajustou goles manualmente para ${v}`,
    addOneToast: '🍺 +1',
    addOneLog: 'Bebeu 1 gole avulso',
    vsMinigameMessage: (name: string) => `${name} caiu na Casa VS — minigame!`,
    minigameOpenMessage: (name: string, turn: number) => `${name} encerrou o Turno ${turn} — beba antes do minigame!`,
    minigameStartFormat: (format: string) => `Formato: ${format.toUpperCase()}`,
    minigameSkipToastVs: 'Minigame VS pulado',
    minigameSkipToast: (turn: number) => `Turno ${turn} encerrado`,
    minigameSkipLogVs: 'Casa VS — minigame pulado',
    minigameSkipLog: (turn: number) => `Turno ${turn} encerrado (minigame pulado)`,
    minigameSkipMessage: 'Minigame cancelado pelo host',
    booStarMessage: (name: string, victimName: string) => `${name} usou o Boo em ${victimName} — roubou estrela!`,
    booCoinMessage: (name: string, victimName: string) => `${name} usou o Boo em ${victimName} — roubou dinheiro!`,
    booStarToast: (victimPart: string) => `👻 +1⭐ roubada${victimPart}!`,
    booStarLog: (victimPart: string) => `Usou o Boo${victimPart} — +1⭐`,
    booCoinToast: (victimPart: string) => `👻 Roubou dinheiro${victimPart}!`,
    booCoinLog: (victimPart: string) => `Usou o Boo${victimPart} — roubou dinheiro`,
    duelChallengeMessage: (name: string, drinks: number) => `${name} te desafiou para um duelo! Beba ${drinks} antes`,
    duelChallengeLog: (label: string, drinks: number) => `Duelo${label} — bebeu ${drinks} (pré-duelo)`,
    duelChallengeToast: (label: string, drinks: number) => `⚔️ Duelo${label}! Pré-duelo: +${drinks}🍺`,
    duelCancelToast: (label: string) => `⚔️ Duelo${label} cancelado`,
    duelCancelLog: (label: string) => `Duelo${label} cancelado`,
    duelCancelledMessage: (name: string) => `${name} cancelou o duelo`,
    duelLostToast: (label: string, drinks: number) => `😅 Perdeu o duelo${label}! 🍺 +${drinks}`,
    duelLostLog: (label: string, drinks: number) => `Perdeu o duelo${label} — bebeu ${drinks} goles`,
    duelWonMessage: (name: string) => `${name} ganhou o duelo!`,
    duelWonToast: (label: string) => `🏆 Ganhou o duelo${label}!`,
    duelWonLog: (label: string) => `Ganhou o duelo${label}`,
  },
};

export type Labels = typeof pt;
export const t = pt;
